In [22]:
from sklearn import datasets
import numpy as np
import math
import pandas as pd
input = pd.read_csv("input.csv")
Y = input["Labeling"]
X = input.drop(columns=["Labeling"])
X = np.asarray(X)
Y = np.asarray(Y)

In [29]:
output = pd.read_csv("output_02.csv")
Y_test = output["Labeling"]
X_test = output.drop(columns=["Labeling"])
X_test = np.asarray(X_test)
Y_test = np.asarray(Y_test)

In [24]:
num_class = len(np.unique(Y))
classes = dict()
cnt = 0
for index,value in enumerate(np.unique(Y)):
    classes[value] = cnt
    cnt+=1

In [26]:
class LogisticReg():
    def __init__(self, lr, iters, num_class, classes):
        self.lr = lr
        self.num_class = num_class
        self.iters = iters
        self.classes = classes
        
    def sigmoid(self,Z):
        Z = Z.astype(float)
        return 1 / (1 + np.exp(-Z))

    def convert_labels(self, Y):
        res = np.zeros(shape = (Y.shape[0],self.num_class))
        for i, value in enumerate(Y): res[i][self.classes[value]] = 1

        return res

    def fit(self,X,Y):
        X = np.insert(X, 0, 1, axis = 1) #add Bias
        self.m , self.n =  X.shape
        self.X = X
        self.Y = self.convert_labels(Y)

        limit = np.sqrt(2 / self.m)
        self.W = np.random.uniform(-limit, limit, (self.n, self.num_class))

        for _ in range(self.iters):
            y_preds = self.sigmoid(self.X.dot(self.W))
            
            gradients = self.X.T.dot(y_preds - self.Y)

            self.W -= self.lr * gradients

        return self
    
    def predict(self, X):

        X = np.insert(X, 0 ,1, axis = 1)
        probas = self.sigmoid(X.dot(self.W))

        return np.argmax(probas, axis=1)
        

In [27]:

def accuracy(y_pred, y_actual,classes):
    right = 0
    wrong = 0
    for index in range(len(y_pred)):
        if (y_pred[index] == classes[y_actual[index]]):
            right+=1
        else:
            wrong+=1

    return (right  / (right + wrong))

In [40]:
LR = LogisticReg(0.0001, 500, num_class,classes)
LR.fit(X,Y)
y_pred = LR.predict(X_test)
for index in range(len(y_pred)): 
    
    print(X_test[index],list(classes.keys())[list(classes.values()).index(y_pred[index])])

[5.1 3.5 1.4 0.2] Iris-setosa
[4.9 3.  1.4 0.2] Iris-setosa
[4.7 3.2 1.3 0.2] Iris-setosa
[4.6 3.1 1.5 0.2] Iris-setosa
[5.  3.6 1.4 0.2] Iris-setosa
[5.7 3.  4.2 1.2] Iris-versicolor
[5.7 2.9 4.2 1.3] Iris-versicolor
[6.2 2.9 4.3 1.3] Iris-versicolor
[5.1 2.5 3.  1.1] Iris-versicolor
[5.7 2.8 4.1 1.3] Iris-versicolor
